on: 
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@v2
    - name: Checkout tag
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        tag_name="${GITHUB_REF##*/}"
        echo Tag $tag_name
        git checkout $tag_name
        sed -i 's/^\(.*Version = \).*$/\1\"'${tag_name}'\"/'  ./common/common.go
        grep -Hn "Version = " ./common/common.go
    - name: Customed builds and release
      run: |
        ./build-all.sh
        assets=("-a" "SHA-1.txt")
        for asset in ./release/*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release edit -d "${assets[@]}" -m "$tag_name: customed release/upx" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
